version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
    ports:
      - 9000:9000
      - 9001:9001
    command: ["server", "--console-address", ":9001", ":9000"]
  content-service:
    build: .
    env_file: .env
    ports:
      - 8000:8000
